spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/calculator
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    #disable liquibase at start-up
    enabled: false


server:
  port: 9003